export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_SUCCEED = 'GET_CONTACTS_SUCCEED';
export const GET_CONTACTS_FAILED = 'GET_CONTACTS_FAILED';

export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const REMOVE_CONTACT_SUCCEED = 'REMOVE_CONTACT_SUCCEED';
export const REMOVE_CONTACT_FAILED = 'REMOVE_CONTACT_FAILED';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_CONTACT_SUCCEED = 'UPDATE_CONTACT_SUCCEED';
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED';

export const CREATE_CONTACT = 'CREATE_CONTACT';
export const CREATE_CONTACT_SUCCEED = 'CREATE_CONTACT_SUCCEED';
export const CREATE_CONTACT_FAILED = 'CREATE_CONTACT_FAILED';